### ISSUE TITLE
PHP version conflict

### ISSUE THREAD

**Issue by uedahiro4** [RCOSDP/LAaaS-docker#26]
READMEの手順1,2まで実施した後、以下のようにしてエラーを回避した。

PHPのバージョンを書き換える

LAaaS-docker/moodle-docker/bin/moodle-docker-compose内の
```
# PHP Version. 
export MOODLE_DOCKER_PHP_VERSION=${MOODLE_DOCKER_PHP_VERSION:-7.2}
```

を7.3 -> 7.2に書き換える．

LAaaS-docker/moodle-docker/bin/moodle-docker-compose.cmd内の

SET MOODLE_DOCKER_PHP_VERSION=7.3 -> SET MOODLE_DOCKER_PHP_VERSION=7.2 に書き換える．
```
IF "%MOODLE_DOCKER_PHP_VERSION%"=="" (
    SET MOODLE_DOCKER_PHP_VERSION=7.2
)
```

LAaaS-docker/moodle-docker/bin/moodle-docker-compose内の

export MOODLE_DOCKER_PHP_VERSION=${MOODLE_DOCKER_PHP_VERSION:-7.3} ->

export MOODLE_DOCKER_PHP_VERSION=${MOODLE_DOCKER_PHP_VERSION:-7.2}に書き換える
```
# PHP Version.
export MOODLE_DOCKER_PHP_VERSION=${MOODLE_DOCKER_PHP_VERSION:-7.2}
```

**Comment by hiroki-sawano** [comment]
#34 で修正済みであるためクローズします。
